# Policy Decision Point for the AI control plane.
#
# input = {stage: "model"|"tool", subject: {sub, tenant_id, role}, model?, prompt?, tool?, resource: {tenant_id}?}
# data.roles     (static file policy/data/roles.json)        role -> models, tools, classifications
# data.registry  (generated by seed, policy/data/registry.json) approved models/tools/prompts + revision
#
# The LLM never decides what it may access: identity supplies the claims, this policy decides,
# the agent runtime enforces (and fails closed if this service is unreachable).
package aicp.authz

import rego.v1

default decision := {"allow": false, "reason": "no_match", "stage": "unknown"}

role_cfg := data.roles[input.subject.role]

approved_models := {m | some m, cfg in data.registry.models; cfg.approved == true}
approved_tools := {t | some t, cfg in data.registry.tools; cfg.approved == true}
approved_prompts := {p | some p, cfg in data.registry.prompts; cfg.approved == true}

requested_model := input.model if {
	input.model != null
	input.model != ""
} else := role_cfg.models[0]

# ---- model stage: which model, which tool schemas, which retrieval filter -------------------
model_allowed if {
	input.stage == "model"
	requested_model in role_cfg.models
	requested_model in approved_models
	input.prompt in approved_prompts
}

allowed_tools := [t | some t in role_cfg.tools; t in approved_tools]

withheld_tools := [t | some t in approved_tools; not t in role_cfg.tools]

decision := {
	"allow": true,
	"stage": "model",
	"model": requested_model,
	"allowed_tools": allowed_tools,
	"withheld_tools": withheld_tools,
	"retrieval_filter": {
		"tenants": [input.subject.tenant_id, "platform"],
		"classifications": role_cfg.classifications,
	},
	"reason": "ok",
	"registry_revision": data.registry.revision,
} if {
	model_allowed
}

decision := {
	"allow": false,
	"stage": "model",
	"reason": model_deny_reason,
	"registry_revision": data.registry.revision,
} if {
	input.stage == "model"
	not model_allowed
}

model_deny_reason := "unknown_role" if {
	not data.roles[input.subject.role]
} else := "model_not_in_role" if {
	not requested_model in role_cfg.models
} else := "unapproved_model" if {
	not requested_model in approved_models
} else := "unapproved_prompt" if {
	not input.prompt in approved_prompts
} else := "denied"

# ---- tool stage: per-call ABAC, resource tenant must equal the caller's tenant ---------------
tool_allowed if {
	input.stage == "tool"
	input.tool in role_cfg.tools
	input.tool in approved_tools
	input.resource.tenant_id == input.subject.tenant_id
}

decision := {
	"allow": true,
	"stage": "tool",
	"tool": input.tool,
	"reason": "ok",
	"registry_revision": data.registry.revision,
} if {
	tool_allowed
}

decision := {
	"allow": false,
	"stage": "tool",
	"tool": input.tool,
	"reason": tool_deny_reason,
	"registry_revision": data.registry.revision,
} if {
	input.stage == "tool"
	not tool_allowed
}

tool_deny_reason := "unknown_role" if {
	not data.roles[input.subject.role]
} else := "tool_not_in_role" if {
	not input.tool in role_cfg.tools
} else := "unapproved_tool" if {
	not input.tool in approved_tools
} else := "tenant_mismatch" if {
	input.resource.tenant_id != input.subject.tenant_id
} else := "denied"
